---
- hosts: database
  user: staterep
  sudo: True

  vars_files:
    - ansible_vars.yml

  tasks:
  - name: Install postgres 9.1
    apt: pkg=postgresql state=latest

  - name: Install postgres 9.1 (dev - for pythons psycopg2)
    apt: pkg=postgresql-server-dev-9.1 state=latest

  - name: Install postgres python interface
    pip: name=psycopg2


- hosts: database

  user: staterep
  sudo: True
  sudo_user: postgres

  vars_files:
    - ansible_vars.yml

  tasks:
  - name: Make sure postgresql is going
    service: name=postgresql state=running

  - name: Create postgres user
    postgresql_user: name=$postgres_user password=$postgres_password

  - name: Create postgres database
    postgresql_db: name=$postgres_name owner=$postgres_user
